overlay = "."
uploaders = ["Andrej Shadura <andrewsh@debian.org>"]
collapse_features = true
summary = "Common utilities for the futures-rs library - Rust source code"

[packages.lib]
test_is_broken = true
