overlay = "."
uploaders = ["Emanuele Rocca <ema@debian.org>"]
collapse_features = true
summary = "Library implementing the Parsec wire protocol"
description = """
Parsec is an abstraction layer that can be used to interact with
hardware-backed security facilities such as the Hardware Security Module (HSM),
the Trusted Platform Module (TPM), as well as firmware-backed and isolated
software services.
.
This package contains an interface library to be used both by the Parsec
service and a Rust Client library. The library contains methods to communicate
using the wire protocol.
.
See https://parallaxsecond.github.io/parsec-book/parsec_client/wire_protocol.html
.
"""

[packages.lib]
test_is_broken = false

[packages."lib+@"]
test_is_broken = true

[packages."lib+fuzz"]
test_is_broken = true

[packages."lib+regenerate-protobuf"]
test_is_broken = true
