overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]

# TODO XXX: uncomment this on next upstream release
# also remove the relevant entries from d/copyright
#excludes = ["lua/**"]

[packages.lib]
depends = ["liblua5.2-dev"]
