overlay = "."
uploaders = ["Blair Noctis <n@sail.ng>"]

# test bins in src/bin
bin = false

[packages.lib]
# Git source has 0.2.5 published with a "unsafe-libyaml-test-suite" pointing
# to `tests/data` (commit b47a144ecd), but the one published on crates.io
# doesn't have this. This test crate has been published on crates.io but later
# yanked.
test_is_broken = true
