overlay = "."
uploaders = [
  "Ximin Luo <infinity0@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
  "Daniel Kahn Gillmor <dkg@fifthhorseman.net>",
]
excludes = [ "benches/**" ]

collapse_features = true
