overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages.lib]
depends = ["libbotan-2-dev"]
test_is_broken = false

[packages."lib+@"]
test_is_broken = true

[packages."lib+botan3"]
test_is_broken = true

[packages."lib+no-std"]
test_is_broken = true
