overlay = "."
uploaders = [
    "Sylvestre Ledru <sylvestre@debian.org>",
    "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+@"]
test_is_broken = true
