overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true
# upstream is missing the testdata, see https://github.com/dignifiedquire/async-tar/issues/43
[packages.lib]
test_is_broken = true
