overlay = "."
uploaders = ["Reinhard Tartler <siretart@tauware.de>"]
excludes = ["doc/rfc/**"]

# requires all tests to be run as root, which is not acceptable during package building
[packages.lib]
test_is_broken = true
