overlay = "."
uploaders = ["Robin Krahl <robin.krahl@ireas.org>"]
summary = "helper crate for darling"

[packages.lib]
description = """
darling_core is a helper crate for darling, a proc-macro library for reading
attributes into structs when implementing custom derives.
"""

[packages."lib+default"]
description = """
darling_core is a helper crate for darling, a proc-macro library for reading
attributes into structs when implementing custom derives.
"""
