overlay = "."
uploaders = ["Arnaud Ferraris <aferraris@debian.org>"]
collapse_features = true

summary = "FFI bindings for PulseAudio's libpulse-mainloop-glib"

[source]
build_depends = ["libpulse-dev"]
