overlay = "."
uploaders = [
  "Robin Krahl <robin.krahl@ireas.org>",
  "kpcyrd <git@rxv.cc>",
]
summary = "helper crate for darling"

[packages.lib]
description = """
darling_macro is a helper crate for darling, a proc-macro library for reading
attributes into structs when implementing custom derives.
"""
