overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
# qoi ships the C bindings; this must be migitated
excludes = ["ext/*"]
# the package tries to test against the nonexistenst libgoi
[packages.lib]
test_is_broken = true
