overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages.lib]
# Tests back-depend on plotters, which isn't even in Cargo.toml
test_is_broken = true
