overlay = "."
uploaders = ["Reinhard Tartler <siretart@tauware.de>"]
collapse_features = true

[packages."lib+async-std"]
test_is_broken = true

[packages."lib+smol_socket"]
test_is_broken = true

[packages."lib+tokio"]
test_is_broken = true

[packages."lib"]
test_is_broken = true
