overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true

# tests fail if no backend is enabled
[packages.lib]
test_is_broken = true

[packages."lib+async-std"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false

[packages."lib+tokio"]
test_is_broken = false
