overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true
[packages.lib]
test_is_broken = false
[packages."lib+fluent-system"]
test_is_broken = true
[packages."lib+gettext-system"]
test_is_broken = true
