overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]
collapse_features = true

#A succesful build requires at least one of the "std" and "alloc" features.
[packages.lib]
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

[packages."lib+alloc"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false

[packages."lib+@"]
test_is_broken = false
