overlay = "."
uploaders = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]
summary = "Structured, extensible, composable logging"

[packages."lib+erased-serde"]
summary = "Structured, extensible, composable logging - feature \"erased-serde\""
