overlay = "."
uploaders = ["Robin Krahl <robin.krahl@ireas.org>"]
summary = "command-line podcast player"

[source]
section = "sound"

[packages.bin]
description = """
podcast is a command-line podcast player.  It can be used to subscribe
to podcasts using RSS feeds and to stream or download podcasts.
"""

