overlay = "."

# needed for tokio 0.2.0, see patch
allow_prerelease_deps = true

uploaders = ["kpcyrd <git@rxv.cc>", "Robin Krahl <robin.krahl@ireas.org>"]

# fail and not needed
excludes = ["benches/**"]
