overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
# needed for generatation, do not remove
[source]
build_depends = ["libgweather-4-dev","libgirepository1.0-dev","gir-rust-code-generator (>= 0.19.1)","xmlstarlet"]
[packages.lib]
test_depends = ["libgweather-4-dev"]
