overlay = "."
uploaders = ["Jochen Sprickerhof <jspricke@debian.org>"]
collapse_features = true

[packages."lib+default"]
test_is_broken = true
[packages."lib+filetime"]
test_is_broken = true
[packages."lib"]
test_is_broken = true
