overlay = "."
uploaders = ["Jelmer Vernooĳ <jelmer@debian.org>"]
collapse_features = true

# These tests are broken because they are missing dependencies on other features:
[packages."lib+anyhow"]
test_is_broken = true

[packages."lib+extension-module"]
test_is_broken = true

[packages."lib+multiple-pymethods"]
test_is_broken = true

[packages."lib+num-bigint"]
test_is_broken = true

[packages."lib+serde"]
test_is_broken = true

#debian's default python version is still 3.11
[packages."lib+abi3-py312"]
test_is_broken = true
