overlay = "."
uploaders = ["Carlos F. Sanz <carlos@sanz.dev>"]
collapse_features = true
allow_prerelease_deps = true
# tests fail when the base0 feature isn't present
[packages.lib]
test_is_broken = true
[packages."lib+@"]
test_is_broken = false
[packages."lib+base0"]
test_is_broken = false
