overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]
collapse_features = true

[packages.lib]
test_is_broken = false
[packages."lib+default"]
test_is_broken = true
[packages."lib+rayon"]
test_is_broken = true
