overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages."lib+arbitrary"]
test_is_broken = true
[packages."lib+bit-vec"]
test_is_broken = true
[packages."lib+bitvec"]
test_is_broken = true
[packages."lib+bytes"]
test_is_broken = true
[packages."lib+chain-error"]
test_is_broken = true
[packages."lib+default"]
test_is_broken = true
[packages."lib+derive"]
test_is_broken = true
[packages."lib"]
test_is_broken = true
[packages."lib+full"]
test_is_broken = true
[packages."lib+fuzz"]
test_is_broken = true
[packages."lib+generic-array"]
test_is_broken = true
[packages."lib+max-encoded-len"]
test_is_broken = true
[packages."lib+parity-scale-codec-derive"]
test_is_broken = true
[packages."lib+serde"]
test_is_broken = true
[packages."lib+std"]
test_is_broken = true
[packages."lib+@"]
test_is_broken = true
