overlay = "."
uploaders = ["Fabio Rafael da Rosa <fdr@fabiodarosa.org>"]
whitelist = ["**/Cargo.toml", "**/lib.rs", "**/build.rs"]
excludes = ["**/fc-*/*", "**/fontconfig/*",
"**/m4/*", "**/src/*",
"**/test/*", "**/doc/*", "conf*", "font*", "ltmain.sh",
"install-sh", "missing", "compile", "depcomp",
"test-driver", "Makefile.in", "Makefile.am", "aclocal.m4",
"Tools.mk", "INSTALL", "ChangeLog",
"NEWS", "AUTHORS", "README", "COPYING"]

[packages.lib]
depends = ["libfontconfig-dev"]
