overlay = "."

(Syntax error to prevent ./update.sh from working)

Debian maintainer's note:

This is only needed for old versions of syn

See https://github.com/dtolnay/syn/commit/c5ab8c6b9fb7bf3f303abac2086485f272a73ebf#diff-80398c5faae3c069e4e6aa2ed11b28c0

We can avoid packaging it for the time being
