overlay = "."
uploaders = [
  "Ximin Luo <infinity0@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]

# https://github.com/m4b/scroll/issues/70
[packages.lib]
test_is_broken = true

# debcargo 2.4.2 doesn't yet honour this but future versions should
# leave it here as documentation of our intent
[packages."lib+std"]
test_is_broken = false
