overlay = "."
uploaders = ["Robin Krahl <robin.krahl@ireas.org>"]
summary = "text diffing and assertion library"

[packages.bin]
section = "utils"
summary = "text diffing tool"
description = """
difference compares two strings and prints a colorful visual representation of
the diff.
"""
