overlay = "."
uploaders = ["Christopher Hoskin <mans0954@debian.org>"]

[source]

homepage = "https://github.com/johannhof/markdown.rs"

[packages.lib]

summary = "native Rust library for parsing Markdown and outputting HTML - Rust source code"

[packages.bin]

section = "text"
summary = "command line utility for parsing Markdown and outputting HTML"
description = """
This package provides a command line utility `markdown` which uses the rust 
markdown crate to parse a markdown file and output HTML.
"""
