overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true

[packages."lib+rustls"]
test_is_broken = true

[packages."lib+tls-rustls"]
test_is_broken = false
