overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true

[packages.lib]
#for time64
depends = ["librust-libc-dev (>= 0.2.153-2)"]

[source]
#for time64
build-depends = ["dpkg-dev (>= 0.2.153-2)"]
