overlay = "."
uploaders = ["Andreas Henriksson <andreas@fatal.se>"]

[source]
section = "utils"

[packages.bin]

summary = "Sync Wifi passwords with macos on ARM Macs"
description = """
This tool can list the WiFi information set up by macOS in NVRAM or
sync it to a local configuration for iwd (but not wpasupplicant).
"""
