overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true

excludes = ["benches/bench.rs"]
# the tests would need a container to run
[packages.lib]
test_is_broken = true

