overlay = "."
uploaders = ["Ximin Luo <infinity0@debian.org>"]
collapse_features = true
excludes = ["benches/*"]

[packages.lib]
extra_lines = ["Breaks: librust-zip-dev (<< 0.6.6)"]

# https://github.com/RustCrypto/block-ciphers/issues/370
[packages."lib+zeroize"]
test_is_broken = true
