overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages.lib]
test_is_broken = false

[packages."lib+async-client"]
test_is_broken = true

[packages."lib+blocking-client"]
test_is_broken = true

[packages."lib+http-client"]
test_is_broken = true

[packages."lib+http-client-curl"]
test_is_broken = true

[packages."lib+http-client-reqwest"]
test_is_broken = true

[packages."lib+serde"]
test_is_broken = true

