semver_suffix = true
overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]
collapse_features = true

# tests fail without default features.
[packages.lib]
test_is_broken = true

# tests fail with "core" feature
[packages."lib+core"]
test_is_broken = true

# tests pass with default features
[packages."lib+default"]
test_is_broken = false

# tests pass with ahash feature.
[packages."lib+ahash"]
test_is_broken = false
