overlay = "."
uploaders = ["Ed Neville <ed-debian@s5h.net>"]

[packages.bin]
section = "utils"
summary = "simple tool to watch logfile throughput"
description = """
Display logfile line throughput. Useful for live comparisson of
server access. E.g. cached vs uncached web access.
"""

[packages.lib]
summary = "simple tool to watch logfile throughput - Rust source code"
description = """
Display logfile line throughput. Useful for live comparisson of
server access. E.g. cached vs uncached web access.
"""

