overlay = "."
uploaders = [
  "Ximin Luo <infinity0@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]
whitelist = ["tests/bins/elf/gnu_hash/*.c"]
collapse_features = true

[packages."lib"]
test_is_broken = true
