overlay = "."
uploaders = [
  "Paul van Tilburg <paulvt@debian.org>",
  "Daniel Kahn Gillmor <dkg@fifthhorseman.net>",
]
bin = false
summary = "Support for concurrent and parallel programming"
collapse_features = true

[packages."lib+@"]
test_is_broken = true

[packages.lib]
test_is_broken = true
