overlay = "."
uploaders = ["Ed Neville <ed-debian@s5h.net>"]
summary = "Human-friendly time expressions"
description = """
Human-friendly time expressions - similar to Python arrow.humanize
"""

collapse_features = true

