overlay = "."
uploaders = ["Reinhard Tartler <siretart@tauware.de>"]

# crate does not pass tests when running `cargo test --no-default-features`
[packages.lib]
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

