overlay = "."
uploaders = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]
collapse_features = true

[packages."lib+backtraces"]
test_is_broken = true

[packages."lib+backtraces-impl-backtrace-crate"]
test_is_broken = true

[packages."lib+futures"]
test_is_broken = true

[packages."lib+guide"]
test_is_broken = true

[packages."lib+unstable-backtraces-impl-std"]
test_is_broken = true
