overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]
summary = "Generate searchable packs of the Unicode character database"

[source]
section = "utils"

[packages.bin]
description = """
A command line tool to generate Unicode tables in Rust source code.

Tables can typically be generated in one of three formats: a sorted sequence of
character ranges, a finite state transducer or a compressed trie. Full support
for name canonicalization is also provided. This tool also supports serializing
regular expressions as DFAs using the regex-automata crate.
"""
