overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]
collapse_features = true

[packages."lib+terminal_size"]
test_is_broken = true

[packages."lib+unicode-width"]
test_is_broken = true
