overlay = "."

XXXX

Please don't package this for the time being.

flate2 was patched to not use miniz, and instead the system zlib. This seems to
be working fine. Typically, crates depend on flate2 rather than miniz directly.

If a crate depends on miniz directly, try persuading them to use flate2 instead.

(If this really needs to be packaged, we should first package miniz as a
C static library Debian package, and *then* package miniz-sys here.)
