overlay = "."
uploaders = ["John Goerzen <jgoerzen@complete.org>"]
excludes = ["**/*.a"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+default"]
test_is_broken = false
