overlay = "."
uploaders = ["Ed Neville <ed-debian@s5h.net>"]

[packages.bin]
section = "utils"
summary = "simple network calculator and lookup tool"
description = """
Process and lookup network addresses from the command line or CSV.
Output has a variety of customisable formats.
"""

[source]
section = "utils"
