overlay = "."
uploaders = ["Maytham Alsudany <maytha8thedev@gmail.com>"]
collapse_features = true

[source]
section = "vcs"

[packages.bin]
summary = "Mailing list style code reviews for GitHub"
description = """
prr is a tool that brings mailing list style code reviews to Github PRs. This
means offline reviews and inline comments, more or less.

To that end, prr introduces a new workflow for reviewing PRs:
  1. Download the PR into a "review file" on your filesystem
  2. Mark up the review file using your favorite text editor
  3. Submit the review at your convenience

For full documentation, please visit https://doc.dxuuu.xyz/prr/.

This package includes the prr program, as well as manual pages and shell
completions for bash, fish, and zsh.
"""
