overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]

# No license present for those svg files; they're also unneccessary
# Exclude fixtures test
excludes = ["fixtures/*.svg","tests/fixtures.rs"]
