overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
bin_name = "bindgen"
[packages.bin]
section="utils"
summary = "Automatically generate Rust FFI bindings to C and C++ libraries"
description = """
bindgen-cli can automatically generates Rust FFI bindings to C and C++ libraries.
The executable and the binary package are named bindgen.
"""
[source]
section = "rust"
