overlay = "."
uploaders = ["Marco Villegas <marco@marvil07.net>", "Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true
# the tests require a database to run
[packages.lib]
test_is_broken = true
