overlay = "."
uploaders = ["James McCoy <jamessan@debian.org>"]

collapse_features = true

# Requires manual setup
[packages."lib+manual_tests"]
test_is_broken = true

# --no-default-features tests fail due to std::mpsc::Sender being !Sync
# https://github.com/notify-rs/notify/issues/503
[packages.lib]
test_is_broken = true

[packages."lib+@"]
test_is_broken = false
