overlay = "."
uploaders = ["Igor Petruk <ipetruk@google.com>"]
collapse_features = true
# The test changes its behavior when run by Debian packaging tools and fails
# More info: https://github.com/Michael-F-Bryan/include_dir/issues/88
excludes = ["tests/integration_test.rs"]
