overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]

[source]
section = "net"

[packages.bin]
summary = "DNS-over-HTTP server proxy"

description = """
A DNS-over-HTTP server proxy in Rust. Add a webserver and you get
DNS-over-HTTPS, which is actually DNS-over-HTTP/2.
"""
