overlay = "."
uploaders = ["Robin Krahl <robin.krahl@ireas.org>"]

[packages."lib+bench"]
test_is_broken = true

[packages."lib+simd"]
test_is_broken = true

[packages."lib+simd_asm"]
test_is_broken = true

[packages."lib+simd_opt"]
test_is_broken = true

