semver_suffix = true
overlay = "."
uploaders = ["Robin Krahl <robin.krahl@ireas.org>", "Alexander Kjäll <alexander.kjall@gmail.com>"]
summary = "proc-macro library for reading attributes into structs"
collapse_features = true
