overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true

# all those features are flaky
[packages."lib+bzip2"]
test_is_broken = true
[packages."lib+deflate"]
test_is_broken = true
[packages."lib+full"]
test_is_broken = true
[packages."lib+full-wasm"]
test_is_broken = true
[packages."lib+tokio-fs"]
test_is_broken = true
[packages."lib+xz"]
test_is_broken = true
[packages."lib+zstd"]
test_is_broken = true
