overlay = "."
uploaders = ["Ximin Luo <infinity0@debian.org>"]

[packages."lib+core"]
test_is_broken = true

[packages."lib+bench"]
# issue with command line parsing in Debian cargo wrapper
# https://salsa.debian.org/rust-team/cargo/-/commit/782307445a611fbb73035dace97709135af6ab0d
test_depends = ["cargo (>> 0.57.0-5)"]
