overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]
summary = "libbzip2 bindings for compression and decompression"
excludes = ["bzip2-*/**"]

[packages.lib]
depends = ["libbz2-dev"]
