semver_suffix = true
overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true
excludes = ["examples/*"]

[packages.lib]
depends = ["librust-wayland-commons-dev (>= 0.29.5-2)"]
