# needed for rust_cid_npm because ipfs-unixfs still depends on cid 0.5
semver_suffix = true
overlay = "."
uploaders = ["Jochen Sprickerhof <jspricke@debian.org>"]

[packages.lib]
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false
