overlay = "."
uploaders = ["Jochen Sprickerhof <jspricke@debian.org>"]
collapse_features = true

[packages."lib+@"]
test_is_broken = true
[packages."lib+alloc"]
test_is_broken = true
[packages."lib+default"]
test_is_broken = true
[packages."lib+multibase"]
test_is_broken = true
[packages."lib+quickcheck"]
test_is_broken = true
[packages."lib+rand"]
test_is_broken = true
[packages."lib+serde"]
test_is_broken = true
[packages."lib+serde-codec"]
test_is_broken = true
[packages."lib+serde_bytes"]
test_is_broken = true
[packages."lib+std"]
test_is_broken = true
[packages."lib"]
test_is_broken = true
