overlay = "."
uploaders = [
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
  "kpcyrd <git@rxv.cc>",
  "Daniel Kahn Gillmor <dkg@fifthhorseman.net>",
]

[packages.lib]
# Reason:
#   --> benches/atomic_cell.rs:1:1
#   |
# 1 | #![feature(test)]
#   | ^^^^^^^^^^^^^^^^^
test_is_broken = true
