overlay = "."
uploaders = [
  "Paride Legovini <paride@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
  "kpcyrd <git@rxv.cc>",
]

whitelist = ["src/errno_dragonfly.c", "test/test_kmod/hello_mod/hello.c"]
collapse_features = true

[packages.lib]
depends = ["librust-libc-dev (>= 0.2.153-6)"]
extra_lines = ["Breaks: librust-vsock-dev (<< 0.2.4-3~), librust-ctrlc-dev (<< 3.2.2-3~), librust-laurel-dev (= 0.6.1-3)"]
