overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true

[packages.lib]
test_is_broken = true
[packages."lib+default"]
test_is_broken = false
[packages."lib+rustc-serialize"]
test_is_broken = false
[packages."lib+serde"]
test_is_broken = true
[packages."lib+serde_json"]
test_is_broken = true
[packages."lib+serde_bytes"]
test_is_broken = true
[packages."lib+disp_hexstring"]
test_is_broken = true



