overlay = "."
uploaders = [
  "Sylvestre Ledru <sylvestre@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]
collapse_features = true

[packages.lib]
description = """
A library for finding occurrences of many patterns at once with SIMD
acceleration in some cases. This library provides multiple pattern search
principally through an implementation of the Aho-Corasick algorithm, which
builds a finite state machine for executing searches in linear time. Features
include case insensitive matching, overlapping matches, fast searching via SIMD
and optional full DFA construction and search & replace in streams.
"""

# src/lib.rs: compile_error!("`std` feature is currently required to build this crate");
test_is_broken = true
