collapse_features = true
# the binary "snap-fixture" is only needed for tests, and has no clear
# documentation. see https://github.com/assert-rs/trycmd/issues/163
bin = false
overlay = "."
uploaders = ["Daniel Kahn Gillmor <dkg@fifthhorseman.net>"]

[packages."lib+document-features"]
# document-features is used to expand feature comments in Cargo.toml to docs in
# src/lib.rs, but we have a reformatted one, which doesn't have those comments
test_is_broken = true

[packages."lib+structured-data"]
# need +json to work
test_is_broken = true
