overlay = "."
uploaders = ["Fabian Grünbichler <debian@fabian.gruenbichler.email>"]

[source]
section = "devel"

[packages.bin]
summary = "Gettext helper for Rust crates"

description = """
xtr is a tool for extracting strings from a Rust crate, for further processing
i18n flows. It is similar to GNU's xgettext, and can extract strings annotated
using the tr macro from its sibling crate 'tr', but also supports other gettext
based localisation crates such as gettext-rs, gettext, rocket_i18n.
"""
