overlay = "."
uploaders = ["Fab Stz <fabstz-it@yahoo.fr>"]

summary = "Traits and macros to embed l10n assets to localize"

collapse_features = true

[packages.lib]
# Tests are failing because uptream doesn't ship the test material (i18n.toml & i18n/)
test_is_broken = true
