overlay = "."
uploaders = ["Jelmer Vernooĳ <jelmer@debian.org>"]
collapse_features = true

[packages.lib]
depends = ["libpython3-all-dev", "python3.12-dev"]

#debian's default python version is still 3.11
[packages."lib+abi3-py312"]
test_is_broken = true
