overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

# see: https://github.com/hickory-dns/hickory-dns/issues/2115
[packages."lib+dns-over-https"]
test_is_broken = true

[packages."lib+dns-over-tls"]
test_is_broken = true

[packages."lib+dnssec"]
test_is_broken = true
