overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>", "James McCoy <jamessan@debian.org>"]
excludes = ["src/**", "include/**"]
collapse_features = true

[packages.lib]
depends = ["libtree-sitter-dev (>= 0.20.7)"]
