overlay = "."
uploaders = ["John Goerzen <jgoerzen@complete.org>"]
collapse_features = true

[packages."lib+mio"]
# error says "the trait `From<mio::net::TcpStream>` is not implemented for `OwnedFd`"
# but it is implemented, in `src/impls_mio.rs`
test_is_broken = true

[packages."lib+socket2"]
# same
test_is_broken = true
