bin = true
overlay = "."
uploaders = ["Igor Petruk <ipetruk@google.com>"]

whitelist=["data/templates/**"]

[source]
section="utils"

[packages.bin]
summary="Shebang interpreter for writing scripts in compiled languages."
description = """
scriptisto is a language-agnostic "shebang interpreter"
that enables you to write scripts in compiled languages.
"""

