overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true
bin = false

[packages."lib+default"]
test_is_broken = true

[packages."lib+multithreaded"]
test_is_broken = true

[packages."lib+@"]
test_is_broken = true
