overlay = "."
uploaders = ["Jelmer Vernooĳ <jelmer@debian.org>"]
# Disable the binary package for now, since some of the
# binaries clash with those in the python3-launchpadlib package.
bin = false
collapse_features = true

[packages.bin]
section = "web"
summary = "utilities for interacting with Launchpad"
description = """
This package provides a number of utilities for interacting with Launchpad.

 * lp-attach: Attach files to a bug report
 * lp-check-membership: Check if a user is a member of a team
 * lp-list-bugs: List bugs in a project
 * lp-set-dupe: Set a bug as a duplicate of another bug
"""
