overlay = "."
uploaders = ["Reinhard Tartler <siretart@tauware.de>"]
collapse_features=true

#a successful build requires exactly one of the "size_16", "size_32" or "size_64" features.
[packages.lib]
test_is_broken = true

[packages."lib+size_16"]
test_is_broken = false

[packages."lib+size_32"]
test_is_broken = false

[packages."lib+size_64"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false

[packages."lib+@"]
test_is_broken = true
