overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true
summary = "Dashboard for progress of async and blocking tasks"

[packages."lib+@"]
test_is_broken = true

[packages."lib+render-line"]
test_is_broken = true

[packages."lib+render-tui"]
test_is_broken = true

[packages."lib+time"]
test_is_broken = true
