overlay = "."
uploaders = ["Fabian Grünbichler <debian@fabian.gruenbichler.email>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false
