overlay = "."
uploaders = [
  "kpcyrd <git@rxv.cc>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

[packages."lib+preserve_order"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false

[packages."lib+@"]
test_is_broken = false
