overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]
collapse_features = true
summary = "Pure Rust implementation of SHA-2"
description = """
Pure Rust implementation of the SHA-2 hash function family including SHA-224, SHA-256, SHA-384, and SHA-512 - feature "asm" and 1 more
This metapackage enables feature "asm" for the Rust sha2 crate, by pulling in
any additional dependencies needed by that feature.

Additionally, this package also provides the "asm-aarch64" feature.
"""

[packages.lib]
# tests only pass on x86_64 and x86 due to asm feature
test_is_broken = true
