overlay = "."
summary = "Display or check licensing of Rust dependencies"
uploaders = ["Matt Kraai <kraai@debian.org>"]
description = """
cargo-lichking is a cargo subcommand that displays or checks the
licensing of Rust dependencies.
"""

[source]
section = "rust"
