overlay = "."
uploaders = [
  "Alexander Kjäll <alexander.kjall@gmail.com>",
  "Holger Levsen <holger@debian.org>"
]

[source]
section = "utils"

[packages.bin]
summary = "Drop-in replacement of gpg and gpgv using the Sequoia OpenPGP implementation."
description = """
gpgv-sq is a feature-complete drop-in replacement of gpgv.

gpg-sq is drop-in replacement of gpg that is not feature-complete.

It currently implements a commonly used subset of the signature
creation and verification commands, the encryption and decryption
commands, the key listing commands, and some miscellaneous commands.

Support for trust models is limited.  Currently, the Web-of-Trust
('pgp') and always trust ('always') are implemented.
"""
