overlay = "."
uploaders = ["Emanuele Rocca <ema@debian.org>"]
collapse_features = true
summary = "Command line tool to communicate with the Parsec service"

[packages.bin]
section = "utils"
description = """
Parsec is an abstraction layer that can be used to interact with
hardware-backed security facilities such as the Hardware Security Module (HSM),
the Trusted Platform Module (TPM), firmware-backed, and isolated software
services.
.
This package provides the command line tool to communicate with the
Parsec service.
"""
