overlay = "."
uploaders = ["Sebastian Ramacher <sramacher@debian.org>"]

[packages.bin]
section = "rust"
description = """
cargo-c is an extension for Cargo, the Rust package manger, that allows
users to build and install C-ABI compatible dynamic and static
libraries. It produces and installs pkg-config files, a static and a
dynamic library, and C headers to be used by any C-compatible software.
"""
