overlay = "."
uploaders = ["James McCoy <jamessan@debian.org>"]
collapse_features = true

[packages.lib]
description = """
Tiny debouncer for rust-notify which filters incoming events and emits only one
event per timeframe per file.
"""
