overlay = "."
uploaders = [
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
  "kpcyrd <git@rxv.cc>"
]
collapse_features = true
[packages.lib]
test_is_broken = true
[packages."lib+std"]
test_is_broken = false
