overlay = "."
uploaders = ["Emanuele Rocca <ema@debian.org>"]
collapse_features = true

summary = "X.509 Subject Public Key Info (RFC5280)"

# Testing the 'arbitrary' feature in isolation fails due to an issue in
# arbitrary itself, fixed upstream in arbitrary 1.2.1. We have 1.1.3 currently
# in sid. See https://github.com/rust-fuzz/arbitrary/pull/131
[packages."lib+arbitrary"]
test_is_broken = true
