overlay = "."
uploaders = ["Blair Noctis <n@sail.ng>"]

collapse_features = true

[source]
section = "utils"

[packages.bin]
summary = "Unified compression and decompression CLI"
description = """
ouch is a unified CLI that compresses to and decompresses from various formats,
currently tar, zip, gz, xz/lzma, bz(2), lz4, sz, zst. It's easy to use and quite
fast.
"""
