overlay = "."
uploaders = ["Robin Krahl <robin.krahl@ireas.org>"]
summary = "add, remove and upgrade Cargo dependencies"

[packages.bin]
section = "rust"
summary = "add, remove and upgrade Cargo dependencies from the command line"
description = """
cargo-edit is an extension for Cargo, the Rust package manger, that allows
users to add, remove and upgrade dependencies by modifying the Cargo.toml file
from the command line.
"""

