overlay = "."
uploaders = ["Sebastian Ramacher <sramacher@debian.org>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+create"]
test_is_broken = true

[packages."lib+itertools"]
test_is_broken = true

[packages."lib+nom"]
test_is_broken = true

[packages."lib+num-rational"]
test_is_broken = true

[packages."lib+parse"]
test_is_broken = true

[packages."lib+serde"]
test_is_broken = true

[packages."lib+serialize"]
test_is_broken = true

[packages."lib+unstable"]
test_is_broken = true
