overlay = "."
uploaders = ["Andreas Henriksson <andreas@fatal.se>"]

[source]
section = "utils"

[packages.bin]
summary = "Read and write nvram variables on ARM Macs"
description = """
This tool can be used to inspect and modify the content of the non-volatile
ram in Apple Silicon Macs.

Warning: May or may not result in you having to perform a dfu restore.
"""

