overlay = "."
uploaders = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]

[packages."lib+@"]
# with no-panic enabled, tests fail to build
test_is_broken = true

[packages."lib+no-panic"]
# with no-panic enabled, tests fail to build
test_is_broken = true
