overlay = "."
uploaders = [
  "Sylvestre Ledru <sylvestre@debian.org>",
  "kpcyrd <git@rxv.cc>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
  "Carlos F. Sanz <carlos@sanz.dev>",
  "Daniel Kahn Gillmor <dkg@fifthhorseman.net>",
]
collapse_features = true

[packages.lib]
extra_lines = ["Breaks: librust-slog-async-dev (<< 2.5.0-2)"]
