overlay = "."
uploaders = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]
collapse_features = true

[packages.lib]
depends = ["libx11-dev"]

[packages."lib+glx"]
depends = ["libgl-dev"]

[packages."lib+xlib"]
depends = ["libx11-dev"]

[packages."lib+xlib_xcb"]
depends = ["libx11-xcb-dev"]

[packages."lib+xcursor"]
depends = ["libxcursor-dev"]

[packages."lib+dpms"]
depends = ["libxext-dev"]

[packages."lib+xft"]
depends = ["libxft-dev"]

[packages."lib+xinput"]
depends = ["libxi-dev"]

[packages."lib+xinerama"]
depends = ["libxinerama-dev"]

[packages."lib+xmu"]
depends = ["libxmu-dev"]

[packages."lib+xrandr"]
depends = ["libxrandr-dev"]

[packages."lib+xrender"]
depends = ["libxrender-dev"]

[packages."lib+xss"]
depends = ["libxss-dev"]

[packages."lib+xt"]
depends = ["libxt-dev"]

[packages."lib+xtst"]
depends = ["libxtst-dev"]

[packages."lib+xf86vmode"]
depends = ["libxxf86vm-dev"]
