semver_suffix = true
overlay = "."
uploaders = [
  "Robin Krahl <robin.krahl@ireas.org>",
  "kpcyrd <git@rxv.cc>",
  "Alexander Kjäll <alexander.kjall@gmail.com>"
]
summary = "helper crate for darling"
collapse_features = true

[packages.lib]
description = """
darling_macro is a helper crate for darling, a proc-macro library for reading
attributes into structs when implementing custom derives.
"""
