overlay = "."
uploaders = ["Andreas Henriksson <andreas@fatal.se>"]

[source]
section = "utils"

[packages.bin]
summary = "Sync Bluetooth pairing keys with macos on ARM Macs"
description = """
This utility can list the bluetooth pairing keys set up by macOS in NVRAM or
sync the content to local configuration for bluez.
"""
