overlay = "."
uploaders = ["Jochen Sprickerhof <jspricke@debian.org>"]
collapse_features = true

[packages."lib+@"]
test_is_broken = true
[packages."lib+default"]
test_is_broken = true
[packages."lib+serde"]
test_is_broken = true
[packages."lib+serde-big-array"]
test_is_broken = true
[packages."lib+serialize_secret_state"]
test_is_broken = true
[packages."lib+std"]
test_is_broken = true
[packages."lib"]
test_is_broken = true
