overlay = "."
uploaders = [
    "Jelmer Vernooĳ <jelmer@debian.org>",
    "Blair Noctis <n@sail.ng>"
]
collapse_features = true

# Note: This crate is packaged with a "custom" d/control, simply removing all
# generated librust-web-sys+FEATURE-dev Depends and use librust-web-sys-dev.
# 
# This is because web-sys has so many features that it would literally break
# some packaging tool, so its maintainer chose to use a d/control and only
# adds features actually used by other crates. We don't bother asking for
# addition. Just use the "base" package since all feature code is always there.
#
# Crates image, plotters-bitmap, plotters-svg, font-kit and handled likewise
# for consistency.


#colormaps feature fails to build with --no-default-features
[packages."lib+colormaps"]
test_is_broken = true

