overlay = "."
uploaders = ["Ananthu C V <weepingclown@disroot.org>"]
collapse_features = true

[packages.lib]
summary = "generator for random names suitable for containers, projects, applications etc."

test_is_broken = true

[packages.bin]
summary = "generator for random names suitable for containers, projects, applications etc."
description = """
A random name generator with names suitable for use in container instances,
project names, application instances, etc.
"""

section = "utils"