overlay = "."
uploaders = ["Jelmer Vernooĳ <jelmer@debian.org>"]

[source]
section = "rust"

[packages.bin]
section = "rust"
description = """
cargo-mutants is a mutation testing tool for Rust. It helps you improve your
program's quality by finding functions whose body could be replaced without
causing any tests to fail.
"""
