overlay = "."
uploaders = ["Jelmer Vernooĳ <jelmer@debian.org>"]

[source]
build_depends = ["llvm", "binutils-mingw-w64-x86-64", "binutils-mingw-w64-i686"]

[packages.lib]
depends = ["llvm", "binutils-mingw-w64-x86-64", "binutils-mingw-w64-i686"]
