overlay = "."
uploaders = ["Fabian Grünbichler <debian@fabian.gruenbichler.email>", "Michael Tokarev <mjt@tls.msk.ru>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+test-utils"]
test_is_broken = false

[packages."lib+@"]
test_is_broken = true
