overlay = "."
uploaders = ["Henry-Nicolas Tourneur <debian@nilux.be>"]

#tests fail to build with --no-default-features
[packages.lib]
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false
