overlay = "."
uploaders = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]

summary = "`macro_attr!` macro for custom macro derives and attributes"

[packages.lib]
description = "Supersedes the `custom_derive` crate."
