overlay = "."
uploaders = ["James McCoy <jamessan@debian.org>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

[packages."lib+no-std-float"]
test_is_broken = false
