overlay = "."
uploaders = ["Daniel Duan <daniel@duan.ca>"]

[source]
section = "utils"
build_depends = ["help2man"]

[packages.bin]
summary = "Tree command, improved"
description = """
A replacement for tree command that uses git ls-files as source of file when
possible.

tre can also create shell aliases that, when executed, opens the file
associated with it with the default editor.
"""
