overlay = "."
uploaders = ["Sebastian Ramacher <sramacher@debian.org>"]

[source]
section = "devel"

[packages.bin]
description = """
drt-tools includes tools to help with typical work of Debian's release
team. Currently, it processes excuses.yaml to check for packages that
require a binNMU for migration to testing, prepares a list of binNMUs
for transitions, and so on. It provides the following sub-commands:
.
 * grep-excuses: Mostly the same as the tool of the same name from
   devscripts.
 * process-excuses: Download and process excuses.yaml to generate a list
   binNMUs for packages that require them for migration. Packages that
   have other issues preventing them from migrating, are not considered.
 * process-unblocks: Download and process excuses.yaml to generate a
   list of unblocks for packages in tpu and some other cases.
 * nmu-transition: Take a list packages copies from ben's output and
   schedules binNMUs.
 * nmu-eso: Produce and schedule a list of rebuilds for packages having
   Built-Using on source packages with Extra-Source-Only: yes set.
"""
