overlay = "."
uploaders = ["Christopher Hoskin <mans0954@debian.org>"]

[source]

homepage = "https://github.com/johannhof/pipeline.rs"

[packages.lib]

summary = "Macro collection to pipe |> your functions calls - Rust source code"

