overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages."lib+@"]
test_is_broken = true

[packages."lib+alloc"]
test_is_broken = true

[packages."lib+encoding-raw"]
test_is_broken = true

[packages."lib+encoding-rzcobs"]
test_is_broken = true

[packages.lib]
test_is_broken = true
