overlay = "."
uploaders = ["Johann Felix Soden <johfel@debian.org>"]
collapse_features = true
summary = "Rust library to log runtime of arbitrary scope"
description = """
 This crate can be used to annotate arbitrary scopes to trace their execution times via log.
 It is part of the gitui project.
"""
