overlay = "."
uploaders = [
    "Alexander Kjäll <alexander.kjall@gmail.com>",
    "Daniel Kahn Gillmor <dkg@fifthhorseman.net>",
    "Holger Levsen <holger@debian.org>"
]
bin_name = "sq-keyring-linter"
[source]
section = "utils"
