overlay = "."
uploaders = ["Ananthu C V <weepingclown@disroot.org>"]
whitelist = ["src/stable_api/compiled.c"]
collapse_features = true

[packages.lib]
depends = ["ruby-dev"]

[packages."lib+@"]
test_is_broken = true

[packages."lib+no-link-ruby"]
test_is_broken = true

[packages."lib+ruby-static"]
test_is_broken = true
