overlay = "."
uploaders = ["Fabian Grünbichler <debian@fabian.gruenbichler.email>"]
collapse_features = true

# tests require the "rand" optional dep
[packages.lib]
test_is_broken = true

[packages."lib+@"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false

[packages."lib+rand"]
test_is_broken = false

[packages."lib+rand_core"]
test_is_broken = false
