overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]
collapse_features = true

[packages."lib+nightly"]
test_is_broken = true

[packages."lib+checked_conversions"]
test_is_broken = true
