overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]
collapse_features = true

# the 'std' feature is required to compile
[packages.lib]
test_is_broken = true

[packages."lib+default"]
test_is_broken = false

[packages."lib+std"]
test_is_broken = false
