overlay = "."
uploaders = ["Arnaud Ferraris <aferraris@debian.org>"]
# We have a package in Debian with this file, let's just use it
excludes = ["src/usb.ids"]

[source]
build_depends = ["usb.ids"]

[packages.lib]
depends = ["usb.ids"]
