overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]
excludes = ["src/bin/**"]

#compile_error!("`alloc` or `std` feature is required for this crate");
[packages.lib]
test_is_broken = true

[packages."lib+alloc"]
test_is_broken = false

[packages."lib+std"]
test_is_broken = false
