overlay = "."
uploaders = ["Ryan Gonzalez <ryan.gonzalez@collabora.com>"]

#the crate requires at least one of the native, unix or windows features
[packages.lib]
test_is_broken = true

[packages."lib+native"]
test_is_broken = false

[packages."lib+unix"]
test_is_broken = false

[packages."lib+windows"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false

