overlay = "."
uploaders = [
  "Ximin Luo <infinity0@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>"
]

collapse_features = true

[packages."lib+@"]
test_is_broken = true
[packages."lib+proc"]
test_is_broken = true
