overlay = "."
uploaders = ["James McCoy <jamessan@debian.org>"]
[packages.lib]
depends = ["libxext-dev", "libgl-dev", "libxcursor-dev", "libxxf86vm-dev", "libxft-dev", "libxinerama-dev", "libxi-dev", "libx11-dev", "libx11-xcb-dev", "libxmu-dev", "libxrandr-dev", "libxtst-dev", "libxrender-dev", "libxss-dev", "libxt-dev"]
