overlay = "."
uploaders = [
  "Ximin Luo <infinity0@debian.org>",
  "kpcyrd <git@rxv.cc>",
]
excludes = ["sleef/**"]

[packages.lib]
depends = ["libsleef-dev (>= 3.4.1-3)"]
#test gives an "unsupported architecture" error on arm64
test_is_broken = true
