overlay = "."
summary = "Brotli decompressor library avoiding the rust stdlib"
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]

collapse_features = true

# The brotli-decompressor program seems like it's just a toy and not production ready
bin = false

# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1032446
# https://github.com/dropbox/rust-brotli-decompressor/issues/23
[packages."lib+@"]
test_is_broken=true
