overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true

# this test tries to connect to google, which is very questionable
excludes = ["tests/google.rs"]

# https://github.com/async-rs/async-tls/issues/51
[packages.lib]
test_is_broken = true
[packages."lib+default"]
test_is_broken = false
