overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>","Fab Stz <fabstz-it@yahoo.fr>"]

[packages.lib]
depends = ["libheif-dev","libsharpyuv-dev", "zlib1g-dev"]
test_depends = ["libheif-dev", "libsharpyuv-dev", "zlib1g-dev"]
