overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
excludes = ["benches/*"]

[packages.lib]
test_is_broken = true

[packages."lib+@"]
test_is_broken = false
[packages."lib+default"]
test_is_broken = false
[packages."lib+getrandom"]
test_is_broken = false

