overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
bin = true
bin_name = "wormhole-rs"
[packages.bin]
section="utils"
summary = "get files from one compute to another, safely"
description = """
Get things from one computer to another, safely.
wormhole-rs is a rust implementation of magic-wormhole.
It provides secure end-to-end encrypted file transfers between computers. 
The endpoints are connected using the same "wormhole code". 
It is fully compatible with the python and go versions.
.
The following new features are available:
 - Automatically copies your code to the clipboard
 - Port forwarding in addition to file transfer (experimental)
 - Send a file to multiple people (experimental)
"""

