overlay = "."
uploaders = [
 "Jelmer Vernooĳ <jelmer@debian.org>",
 "Daniel Kahn Gillmor <dkg@fifthhorseman.net>",
]
collapse_features = true

[packages."lib+@"]
# When --all-features is supplied, the combination of sqlcipher and
# buildtime_bindgen fares poorly with debian's outdated sqlcipher.
# When https://bugs.debian.org/1017577 is fixed, this should be
# cleared.
test_is_broken = true

# The following tests only pass when *also* using the
# buildtime_bindgen feature.  This is workaround (a) from
# https://bugs.debian.org/1018066
[packages."lib+array"]
test_is_broken = true
[packages."lib+csvtab"]
test_is_broken = true
[packages."lib+release_memory"]
test_is_broken = true
[packages."lib+series"]
test_is_broken = true
[packages."lib+unlock_notify"]
test_is_broken = true
[packages."lib+vtab"]
test_is_broken = true
[packages."lib+window"]
test_is_broken = true
