overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]

[source]
section = "utils"

[packages.bin]
summary = "Make production Rust binaries auditable"
description = """
Know the exact crate versions used to build your Rust
executable. Audit binaries for known bugs or security
vulnerabilities in production, at scale, with
zero bookkeeping.

This works by embedding data about the dependency
tree in JSON format into a dedicated linker section
of the compiled executable.
"""