overlay = "."
uploaders = ["Ananthu C V <weepingclown@disroot.org>"]

[packages.lib]
summary = "Macro to repeat sequentially indexed copies of a fragment of code"
description = """
librust-seq-macro-dev - Macro to repeat sequentially indexed copies of
a fragment of code.
"""
