overlay = "."
uploaders = ["Ananthu C V <weepingclown@disroot.org>"]
collapse_features = true

[packages.lib]
summary = "parse and describe keys - helps incorporate keybindings in terminal applications"

test_is_broken = true

[packages."lib+serde"]
test_is_broken = true