overlay = "."
uploaders = ["Blair Noctis <n@sail.ng>"]

[packages.lib]
# tests::with_default_pager fails when it's the last test being run
# https://gitlab.com/imp/pager-rs/-/issues/15
test_is_broken = true
