overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true
summary = "Adaptor between compression crates and Rust's async types"
# Unfortunately this is needed as the build fails otherwise
excludes = ["examples/*", "tests/*"]
