overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]

# the dependency suppositions is missing, and there is a dependency-loop between that package and this one
[packages."lib+@"]
test_is_broken = true
