overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
[source]
build_depends = ["libgtk-4-dev","xmlstarlet","libgirepository1.0-dev","gir-rust-code-generator (>= 0.19.1)"]

[packages."lib+v4_14"]
test_is_broken = true
[packages."lib+v4_16"]
test_is_broken = true

