overlay = "."
uploaders = [
  "Ximin Luo <infinity0@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]

collapse_features = true

[packages.lib]
extra_lines = ["Breaks: librust-cargo-dev (<= 0.43.1-4), librust-debcargo-dev (<= 2.4.4-1)"]

[packages."lib+unstable"]
test_is_broken = true

[packages."lib+@"]
test_is_broken = true
