overlay = "."
uploaders = ["Ximin Luo <infinity0@debian.org>"]

summary = "Wait on a child process with a timeout, cross-platform"

# the binaries are a bit useless and not worth a Debian package for
# note the "sleep" program cannot replace /bin/sleep from coreutils
# as it does not support float arguments
bin = false
