overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
# needed to re-generate the code, do not remove
[source]
build_depends = ["libgraphene-1.0-dev","gir-rust-code-generator (>= 0.19.1)","libgirepository1.0-dev","xmlstarlet"]
[packages.lib]
test_depends = ["libgraphene-1.0-dev"]

#the current version of libgraphene-1.0-dev is too old
[packages."lib+v1_12"]
test_is_broken = true

