overlay = "."
uploaders = ["Fabian Grünbichler <f.gruenbichler@proxmox.com>"]
summary = "Self-contained Cargo.lock parser"
collapse_features = true

[source]
build_depends = ["librust-gumdrop-0.8+default-dev", "librust-petgraph-0.6+default-dev"]

[packages.bin]
section = "rust"
