overlay = "."
uploaders = [
  "Robin Krahl <robin.krahl@ireas.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]
summary = "drop-in replacements for assert macros with colorful diffs"

[packages.lib]
test_is_broken = true

[packages."lib+default"]
test_is_broken = false

[packages."lib+std"]
test_is_broken = false

[packages."lib+alloc"]
test_is_broken = false
