overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+@"]
test_is_broken = true

[packages."lib+default"]
test_is_broken = true

[packages."lib+metadata"]
test_is_broken = true
