overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]

[source]
section = "utils"
build_depends = ["scdoc"]

[packages.bin]
section = "utils"
summary = "Bruteforce with a stream of permutations of a specific pattern"
description = """
Bruteforce with a stream of permutations of a specific pattern. Also prints a
progress bar and calculates an ETA.

In case you tend to forget your LUKS password as well.
"""
