overlay = "."
uploaders = ["Robin Krahl <robin.krahl@ireas.org>"]
summary = "test CLI applications"

# assert_cli contains the assert_fixture binary for its own unit tests
# (tests/cargo.rs) -- we don’t have to create a binary package for that
bin = false
