overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]
bin_name = "rust-diffutils"

[source]
section = "utils"

[packages.bin]
summary="Rust implementation of GNU diffutils"
description="Propose an dropped in replacement for diff."
section = "utils"
