overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

bin = false

[packages."lib+document-features"]
test_is_broken = true

[packages."lib+unstable"]
test_is_broken = true