overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>", "Alexander Kjäll <alexander.kjall@gmail.com>"]

collapse_features = true
description = """
Rust implementation of the XXHash and XXH3 algorithms
"""

[packages."lib+@"]
test_is_broken = false

[packages."lib+std"]
test_is_broken = false

[packages."lib+digest"]
test_is_broken = true

[packages."lib+rand"]
test_is_broken = true

[packages."lib+serde"]
test_is_broken = true

[packages."lib+serialize"]
test_is_broken = true

[packages."lib"]
test_is_broken = true
