overlay = "."
whitelist = ["c/**"]
uploaders = ["karthek <mail@karthek.com>"]
collapse_features = true

#some features are mutually exclusive.
[packages."lib+@"]
test_is_broken = true

#fails to build on architectures that don't have neon
[packages."lib+neon"]
test_is_broken = true
