overlay = "."
uploaders = ["Timo Aaltonen <tjaalton@debian.org>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+arcache"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false

[packages."lib+maps"]
test_is_broken = false

[packages."lib+@"]
test_is_broken = true
