overlay = "."
uploaders = ["Blair Noctis <n@sail.ng>"]
collapse_features = true

[packages.lib]
# functionalities are enabled through features, bare lib means nothing to use
test_is_broken = true

[packages."lib+default"]
# default feature enables all other features
test_is_broken = false
