overlay = "."
uploaders = ["Paride Legovini <paride@debian.org>",
             "kpcyrd <git@rxv.cc>"]
collapse_features = true

# serde and with-serde tests are broken with --no-default-features
# see https://github.com/servo/unicode-bidi/issues/83
[packages."lib+serde"]
test_is_broken = true

[packages."lib+with_serde"]
test_is_broken = true

