overlay = "."
bin_name = "b3sum"
uploaders = ["karthek <mail@karthek.com>"]

[source]
homepage= "https://github.com/BLAKE3-team/BLAKE3"
section= "utils"

[packages.bin]
summary= "Command line tool for the BLAKE3 hash"
description= """
 BLAKE3 is a cryptographic hash function that is much faster than MD5, SHA-1, 
 SHA-2, SHA-3, and BLAKE2 and
 Secure, unlike MD5 and SHA-1. And secure against length extension.
 Note, This package includes binary "b3sum" which is built from official 
 multithreaded  implementation of BLAKE3 in rust.
"""
