overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true

[packages.lib]
test_is_broken = true
[packages."lib.default"]
test_is_broken = false
[packages."lib+native-tls"]
test_is_broken = false
[packages."lib+reqwest"]
test_is_broken = false
[packages."lib+rustls-tls"]
test_is_broken = false
