overlay = "."
uploaders = ["Emmanuel Arias <eamanu@yaerobi.com>"]
summary = "light utility helping with unix mode representation"

[packages.bin]
section = "utils"
summary = "utility to help with unix mode representation"
description = """
A light utility helping with unix mode representation, with strong types to avoid misusing constants.
.
The Mode struct implements Display and prints as "rwxrwxrwx".
"""
