overlay = "."
uploaders = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]
collapse_features = true

#Code fails to build with error that alloc feature must be enabled
[packages.lib]
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

[packages."lib+alloc"]
test_is_broken = false

