overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]

[packages.lib]
# this crate is meant for wasm32-* targets, so tests are expected to not even compile.
# we could install libstd-rust-dev-wasm32-cross and pass --target wasm32-unknown-unknown,
# however cargo doesn't support cross-compiling doctests yet https://github.com/rust-lang/cargo/issues/4471
test_is_broken = true
