overlay = "."
uploaders = [
  "Ximin Luo <infinity0@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]
excludes = ["src/libbacktrace/**"]
whitelist = ["src/android-api.c"]

[packages.lib]
# Disable because might depend on nightly
test_is_broken = true
