overlay = "."
uploaders = [
 "Ximin Luo <infinity0@debian.org>",
 "Daniel Kahn Gillmor <dkg@fifthhorseman.net>",
]
excludes = ["curl/**"]
allow_prerelease_deps = true

[packages.lib]
depends = ["libcurl4-gnutls-dev"]
