overlay = "."
uploaders = ["Jochen Sprickerhof <jspricke@debian.org>"]
collapse_features = true

[packages."lib+blake2b"]
test_is_broken = true
[packages."lib+blake2s"]
test_is_broken = true
[packages."lib+blake3"]
test_is_broken = true
[packages."lib+default"]
test_is_broken = true
[packages."lib+digest"]
test_is_broken = true
[packages."lib+ripemd"]
test_is_broken = true
[packages."lib+serde"]
test_is_broken = true
[packages."lib+sha1"]
test_is_broken = true
[packages."lib+sha2"]
test_is_broken = true
[packages."lib+sha3"]
test_is_broken = true
[packages."lib+std"]
test_is_broken = true
[packages."lib+strobe"]
test_is_broken = true
[packages."lib"]
test_is_broken = true
