overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]

collapse_features = true

[packages.lib]
# some tests require std but they are also configured to run on the no-std feature
# there is a proper way to fix it, see the git history of this directory for an
# example patch, but it is simply unmaintainable
#
# update: features are even more entangled, for now just mark all flaky.
test_is_broken = true
