overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+document-features"]
test_is_broken = true

[packages."lib+gix-features"]
test_is_broken = true

[packages."lib+serde"]
test_is_broken = true

[packages."lib+@"]
test_is_broken = true
