overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true
[packages.lib]
test_is_broken = true
[packages."lib+sqlite3-src"]
test_is_broken = true
[packages."lib+default"]
test_is_broken = false
[packages."lib+linkage"]
test_is_broken = false
