semver_suffix = true
overlay = "."
uploaders = ["Robin Krahl <robin.krahl@ireas.org>", "Alexander Kjäll <alexander.kjall@gmail.com>"]
summary = "helper crate for darling"
collapse_features = true

[packages.lib]
description = """
darling_core is a helper crate for darling, a proc-macro library for reading
attributes into structs when implementing custom derives.
"""

[packages."lib+default"]
description = """
darling_core is a helper crate for darling, a proc-macro library for reading
attributes into structs when implementing custom derives.
"""
