overlay = "."
uploaders = ["Henry-Nicolas Tourneur <debian@nilux.be>"]
collapse_features = true

#tests require the "full" feature.
[packages.lib]
test_is_broken = true

[packages."lib+full"]
test_is_broken = false
