overlay = "."
uploaders = ["Andrej Shadura <andrewsh@debian.org>"]
collapse_features = true

[packages.lib]
# cubicbez::tests::cubicbez_signed_area_linear is flaky:
# compares 0.5000000000000001 and 0.5
test_is_broken = true
