overlay = "."
uploaders = ["James McCoy <jamessan@debian.org>"]
summary = "Encoding characters in HTML/decoding HTML entities"
# Data files used for the benchmarks aren't included in the crate
excludes = ["benches/*"]
