overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true

[packages.lib]
test_depends = ["g++"]

[packages."lib+experimental-enum-variants-from-header"]
test_is_broken = true
