overlay = "."
uploaders = ["Andreas Henriksson <andreas@fatal.se>"]

[source]
section = "sound"
build_depends = ["systemd-dev"]

[packages.bin]
summary = "software Smart Amp implementation"
description = """
 speakersafetyd is a userspace daemon that implements an analogue of the Texas
 Instruments Smart Amp speaker protection model.
 .
 Apple Silicon Macs mostly use amp chip which provides sense lines for the
 voltage and current across the voice coil of the connected speaker. These
 codecs are designed to be used in embedded applications where device firmware
 takes this information and uses it to protect the speaker from damage.
 .
 speakersafetyd is an implementation of a speaker protection model. It solves
 the problem described above by allowing parties interested in compatible
 devices to quickly and easily implement a speaker protection model for those
 devices. Only Apple Silicon Macs under Linux are currently supported, however
 the model applies to all loudspeakers. The daemon itself should be easy enough
 to adapt for any device that provides V/ISENSE data in a manner similar to
 TAS2764.
"""
