overlay = "."
uploaders = ["Emanuele Rocca <ema@debian.org>"]
collapse_features = true

# Do not generate a package for the binary crate. /usr/bin/rcgen just prints a
# certificate and private key to standard output.
bin = false

