overlay = "."
uploaders = ["Wolfgang Silbermayr <wolfgang@silbermayr.at>"]

[source]
section = "utils"
build_depends = ["help2man", "librust-tempfile-dev"]

[packages.bin]

section = "utils"

summary = "Strip rustdoc comments from source code"
description = """
rustdoc-stripper is a tool used to remove rustdoc comments from your code and
save them in a comments.cmts file if you want to regenerate them.
"""
