overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
# this is needed for generating the code, do not remove
[source]
build_depends = ["gir-rust-code-generator (>= 0.19.1)", "libgirepository1.0-dev", "xmlstarlet"]
