overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
summary = "Simple bit field trait providing bit methods"
description = """
Crate which provides the BitField trait, which provides methods for
operating on individual bits and ranges of bits on Rust's integral types.
"""