overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+arbitrary"]
test_is_broken = true

[packages."lib+proptest"]
test_is_broken = true

[packages."lib+serde"]
test_is_broken = true
