overlay = "."
uploaders = ["Henry-Nicolas Tourneur <debian@nilux.be>"]

[packages.bin]
section = "misc"
summary = "Utility to share your GPS device on local network"
description = """
gps-share has two goals:
.
- Share your GPS device on the local network so that all machines in your home
  or office can make use of it.
- Enable support for standalone (i-e not part of a cellular modem) GPS devices
  in Geoclue. Since Geoclue has been able to make use of network NMEA sources
  since 2015, gps-share works out of the box with Geoclue.
.
The latter means that it is a replacement for GPSD and Gypsy. 
While "why not GPSD?" has already been documented, Gypsy has
been unmaintained for many years now. I did not feel like reviving a dead
project and I really wanted to code in Rust so I decided to create gps-share.
"""
