overlay = "."
uploaders = [
  "Ximin Luo <infinity0@debian.org>",
  "kpcyrd <git@rxv.cc>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]
excludes = ["ci/**"]

# the unversioned llvm/clang packages are currently broken in mips64el testing
# which is getting in our way.
[source]
build_depends = ["llvm | llvm-15 [mips64el]", "clang | clang-15 [mips64el]"]

[packages.lib]
depends = ["libclang-dev | libclang-15-dev [mips64el]", "llvm | llvm-15 [mips64el]", "clang | clang-15 [mips64el]"]
test_depends = ["llvm", "clang"]

[packages."lib+@"]
# The `runtime` and `static` features can't be combined (see build.rs)
test_is_broken = true

[packages."lib+static"]
# libclang.a doesn't exist
test_is_broken = true
