overlay = "."
uploaders = ["kpcyrd <git@rxv.cc>"]

[source]
section = "net"
build_depends = ["python3-sphinx", "bash-completion"]

[packages.bin]
section = "net"
depends = ["publicsuffix", "libcap2-bin"]
summary = "Semi-automatic OSINT framework and package manager"
description = """
sn0int is a semi-automatic OSINT framework and package manager. It was built
for IT security professionals and bug hunters to gather intelligence about a
given target or about yourself. sn0int is enumerating attack surface by
semi-automatically processing public information and mapping the results in
a unified format for followup investigations.
"""
