overlay = "."
uploaders = ["Jelmer Vernooĳ <jelmer@debian.org>"]

[source]
section = "net"

[packages.bin]
summary = "Networking services for small/home networks"
description = """
Erbium provides networking services for use on small/home networks.

Its aim is to provide sensible defaults out of the box that can be
overridden when needed.

Erbium currently supports both DNS and DHCP.
"""
