overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+default"]
test_is_broken = false
[packages."lib+std"]
test_is_broken = false
[packages."lib+threading"]
test_is_broken = true
