overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]

# We do not want to run the benchmark tests as they require unstable
excludes = ["benches/**", "examples/**"]
collapse_features = true
