overlay = "."
uploaders = ["Dylan Aïssi <daissi@debian.org>", "Arnaud Ferraris <aferraris@debian.org>"]
collapse_features = true

[packages.bin]
section = "utils"
summary = "Rockchip USB utility"
description = """
rockusb is an independent re-implementation of the Rockchip USB
protocol used to communicate with various Rockchip processors. It
allows one to read information about the processor or the flash memory,
read and write files to and from flash, reset the device and various
other commands.
"""
