overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]

collapse_features = true

[packages.lib]
extra_lines = ["Breaks: librust-globset-dev (<= 0.4.10-1)"]

[packages."lib+unicode"]
test_is_broken = true
