overlay = "."
uploaders = [
 "Ximin Luo <infinity0@debian.org>",
 "Daniel Kahn Gillmor <dkg@fifthhorseman.net>",
]
collapse_features = true
summary = "Generate 'cargo:env' instructions in 'build.rs'"

# Some tests expect to be run from a git repo, but we run
# them from an unpacked crate.  see:
# https://github.com/rustyhorde/vergen/issues/140
[packages."lib+git"]
test_is_broken = true
[packages."lib+rustc"]
test_is_broken = true
