overlay = "."
uploaders = ["Andrej Shadura <andrewsh@debian.org>"]

[packages.bin]
section = "vcs"
description = """
git-absorb is a port of hg absorb to Git.

git absorb automatically identifies which commits are safe to modify,
and which indexed changes belong to each of those commits. It then writes
fixup! commits for each of those changes. These fixups can later be folded
into the feature branch with Git's built-in autosquash functionality.
"""
