overlay = "."
uploaders = ["James McCoy <jamessan@debian.org>"]
summary = "command-line for Tree-sitter parsers"

[packages.bin]
section = "devel"
recommends = ["gcc | c-compiler", "nodejs", "node-gyp", "emscripten"]

[packages.lib]
depends = ["librust-tree-sitter-dev (>= 0.20.9), libtree-sitter-dev (>= 0.20.7)"]
test_depends = ["g++"]
