overlay = "."
uploaders = ["Emanuele Rocca <ema@debian.org>"]
collapse_features = true

[packages.lib]
# The tests assume there is a tpm_server listening on port 2321, but tpm_server
# is not in Debian. See https://downloads.sourceforge.net/project/ibmswtpm2/
test_is_broken = true
