overlay = "."
uploaders = ["Henry-Nicolas Tourneur <debian@nilux.be>", "Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true
# Some tests are written in C and get built when `cargo test` is executed.
whitelist = ["tests/*.c"]

[packages.lib]
depends = ["libhandy-1-dev"]
