overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true

[packages.lib]
depends = ["libshumate-dev"]

# needed to regenerate the code, do not remove
[source]
build_depends = ["libshumate-dev","libgirepository1.0-dev","gir-rust-code-generator(>= 0.19.1)","xmlstarlet","libgraphene-1.0-dev"]

