overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]

[source]
build_depends = ["bsdutils <!nocheck>"]

[packages.lib]
# Disable because of https://github.com/softprops/atty/issues/39
# stdin closed
test_is_broken = true
