overlay = "."
uploaders = ["Niklas Claesson <nicke.claesson@gmail.com>"]

[source]
build_depends = ["help2man", "librust-clap-2+default-dev"]
# extra "clap" b-d is needed because [[bin]] has extra required-features

[packages.bin]
section = "devel"
