overlay = "."
uploaders = ["Ian Jackson <ijackson@chiark.greenend.org.uk>"]
summary = "Slightly more flexible Cow"
description = """
roughly to T: Borrow<R> as alloc::borrow::Cow is to B: ToOwned
"""

excludes = [
	"badges.rs",
	"cargo_badges.rs",
	"constants_.rs",
	"headings.rs",
	"readme.rs",
	"version-numbers.rs",
]
