overlay = "."
uploaders = ["Daniel Kahn Gillmor <dkg@fifthhorseman.net>", "Holger Levsen <holger@debian.org>"]
collapse_features = true

# see https://bugs.debian.org/945560
[packages."lib+bzip2"]
test_is_broken = true
[packages."lib+compression-deflate"]
test_is_broken = true
