overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
whitelist = ["tests/*.c"]
collapse_features = true
# this is needed for regeneration, do not delete
[source]
build_depends = ["libgtk-4-dev (>= 4.12)","libgraphene-1.0-dev","libgirepository1.0-dev","gir-rust-code-generator (>= 0.19.1)","xmlstarlet"]
[packages.lib]
test_depends = ["libgtk-4-dev"]

[packages."lib+v4_14"]
# GTK4 4.14 is not in Debian yet
test_is_broken = true
