overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]

XXXX

Please don't package this as-is.

The "rustfmt" on crates.io is deprecated and out-of-date, and uses very old
libraries, and hasn't been maintained in a year.

Eventually they plan to stabilise "rustfmt-nightly".
