overlay = "."
uploaders = ["Claudius Heine <ch@denx.de>"]
collapse_features = true


[packages.lib]
# no-default-features is broken since it requires std to run tests
test_is_broken = true

[packages."lib+std"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false
