overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
collapse_features = true

#on arm64 those features fail; the pass fine on every other arch. 
# See https://github.com/rusticstuff/simdutf8/issues/74
[packages.lib]
test_is_broken = false
[packages."lib+@"]
test_is_broken = true
[packages."lib+aarch64_neon_prefetch"]
test_is_broken = true
