overlay = "."
uploaders = ["Clay Stan <claystan97@gmail.com>"]

[packages.bin]
summary = "Rust library to handle configuration fragments"
description = """
 This crate provides helpers to scan configuration fragments on disk.
 The goal is to help in writing Linux services which are shipped as part of a Reproducible OS.
"""
