overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
whitelist = ["tests/*.c"]

# needed to regenerate the code, do not remove
[source]
build_depends = ["libadwaita-1-dev","libgirepository1.0-dev","gir-rust-code-generator (>= 0.19.1)","xmlstarlet","libgraphene-1.0-dev"]
[packages.lib]
test_depends = ["libadwaita-1-dev"]
