overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]

collapse_features = true

#autopkgtest fails for all features except f32, f64 and default
[packages.lib]
test_is_broken = true
[packages."lib+f32"]
test_is_broken = false
[packages."lib+f64"]
test_is_broken = false
[packages."lib+default"]
test_is_broken = false
