overlay = "."
uploaders = ["Matthias Geiger <matthias.geiger1024@tutanota.de>"]
whitelist = ["tests/constant.c", "tests/layout.c"]
collapse_features = true
[packages.lib]
depends = ["libtracker-sparql-3.0-dev"]
