overlay = "."
uploaders = ["Sylvestre Ledru <sylvestre@debian.org>"]

[source]
section = "utils"
build_depends = ["help2man"]

[packages.bin]
summary = "Demangle Rust symbol names using rustc-demangle"
description = """
rustfilt works similarly to c++filt, in that it accepts mangled symbol names as
command line arguments, and if none are provided it accepts mangled symbols
from stdin. Demangled symbols are written to stdout.
"""
