overlay = "."
uploaders = ["James McCoy <jamessan@debian.org>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+@"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false
