overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
# Some tests are written in C and get built when `cargo test` is executed.
whitelist = ["tests/*.c"]
# this is needed for generating the code, do not remove
[source]
build_depends = ["libglib2.0-dev (>= 2.80)", "gir-rust-code-generator (>= 0.19.1)", "libgirepository1.0-dev", "xmlstarlet"]
[packages.lib]
test_depends = ["libglib2.0-dev (>= 2.80)"]
