overlay = "."
uploaders = ["Marc Dequènes (Duck) <Duck@DuckCorp.org>"]
collapse_features = true
# see copyright file for font removal rational
# removing tests that fails due to removal
excludes = ['fonts/font.ttf', 'tests/owned_ttf.rs', 'tests/preparse.rs']

[packages.lib]
test_is_broken = true
