overlay = "."
uploaders = [
  "Sylvestre Ledru <sylvestre@debian.org>",
  "Wolfgang Silbermayr <wolfgang@silbermayr.at>",
]
collapse_features = true

[source]
build_depends = ["librust-tempfile-dev"]

[packages.bin]
section = "utils"

[packages.lib]
test_is_broken = true

[packages."lib+ansi_term"]
test_is_broken = false

[packages."lib+default"]
test_is_broken = false

[packages."lib+gnu_legacy"]
test_is_broken = false

[packages."lib+nu-ansi-term"]
test_is_broken = false
