overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
# this is need for generation, do not remove
[source]
build_depends = ["libgtk-4-dev","libgraphene-1.0-dev","libgirepository1.0-dev","gir-rust-code-generator (>= 0.19.1)","xmlstarlet"]
#broken because the C bindings are too old
[packages."lib+v4_14"]
test_is_broken = true

