overlay = '.'
uploaders = ['Blair Noctis <n@sail.ng>']
# not needed as we use Debian packaged mimalloc
excludes = ['c_src/*']
collapse_features = true

[packages.lib]
depends = ['libmimalloc-dev']

[packages."lib+extended"]
# "shouldn't be adding tests for the experimental enum values"
# https://github.com/purpleprotocol/mimalloc_rust/issues/84
test_is_broken = true
