overlay = "."
uploaders = ["Matthias Geiger <werdahias@riseup.net>"]
collapse_features = true
# Some tests are written in C and get built when `cargo test` is executed.
whitelist = ["tests/*.c"]
# needed to regenerate the code, do not remove
[source]
build_depends = ["libgtk-3-dev","gir-rust-code-generator (>= 0.19.0)","libgirepository1.0-dev","xmlstarlet"]
[packages.lib]
test_depends = ["libgtk-3-dev"]
