overlay = "."
uploaders = ["Loren M. Lang <lorenl@north-winds.org>"]
collapse_features = true

[packages."lib+@"]
test_is_broken = true

[packages."lib+publicsuffix"]
test_is_broken = true

[packages."lib+serde"]
test_is_broken = true
