semver_suffix = false
overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]

# doc-tests depend on enum-map, which is outdated at the time test is run
[packages.lib]
test_is_broken = true
