overlay = "."
uploaders = ["Jelmer Vernooĳ <jelmer@debian.org>"]
collapse_features = true
test_is_broken = true

[packages."lib"]
depends = ["python3-breezy"]
test_is_broken = true

[packages."lib+debian"]
depends = ["brz-debian"]
test_is_broken = true
