overlay = "."
uploaders = ["Fabian Grünbichler <debian@fabian.gruenbichler.email>"]
collapse_features = true

# doc tests only work with default features
[packages.lib]
test_is_broken = true

[packages."lib+default"]
test_is_broken = false

[packages."lib+@"]
test_is_broken = false
