overlay = "."
uploaders = ["Alexander Kjäll <alexander.kjall@gmail.com>"]
collapse_features = true

[packages."lib"]
test_is_broken = true

[packages."lib+_protobuf"]
test_is_broken = true

[packages."lib+criterion"]
test_is_broken = true
