overlay = "."
uploaders = ["Arnaud Ferraris <aferraris@debian.org>"]
collapse_features = true

[packages.lib]
test_is_broken = true

[packages."lib+gdk-pixbuf"]
test_is_broken = true

[packages."lib+default"]
test_is_broken = false

[packages."lib+async-std"]
test_is_broken = false

[packages."lib+tokio"]
test_is_broken = false

[packages."lib+@"]
test_is_broken = false
